# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gateway.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgateway.proto\"v\n\x0eTransitGateway\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03\x61rn\x18\x02 \x01(\t\x12\r\n\x05state\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x10\n\x08owner_id\x18\x05 \x01(\t\x12\x15\n\rcreation_time\x18\x06 \x01(\t\"\x1f\n\rRegionRequest\x12\x0e\n\x06region\x18\x01 \x01(\t2F\n\x0eGatewayService\x12\x34\n\x11GetTransitGateway\x12\x0e.RegionRequest\x1a\x0f.TransitGatewayb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gateway_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TRANSITGATEWAY._serialized_start=17
  _TRANSITGATEWAY._serialized_end=135
  _REGIONREQUEST._serialized_start=137
  _REGIONREQUEST._serialized_end=168
  _GATEWAYSERVICE._serialized_start=170
  _GATEWAYSERVICE._serialized_end=240
# @@protoc_insertion_point(module_scope)
